In [415]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix

In [366]:
df=pd.read_csv("C:\\Users\\HP\\Downloads\\uci-census-income\\adults_train.csv")
test=pd.read_csv("C:\\Users\\HP\\Downloads\\uci-census-income\\adults_test.csv")

In [369]:
df=df[df['Work Class ']!=' ?']
df=df[df['Occupation']!=' ?']
df=df[df['Native Country']!=' ?']
for i in range(len(df)):
    if df.iloc[i,13] not in [' United-States',' Mexico']:
        df.iloc[i,13]='Other Country'
for i in range(len(df)):
    if df.iloc[i,3] in [' 1st-4th',' Preschool',' 5th-6th',' 10th', ' 12th',' 11th', ' 7th-8th',' 9th']:
        df.iloc[i,3]='12th and below'
for i in range(len(df)):
    if df.iloc[i,1] not in [' Private']:
        df.iloc[i,1]=' Not Private'
for i in range(len(df)):
    if df.iloc[i,5]  in [' Married-spouse-absent',' Separated',' Married-AF-spouse',' Widowed']:
        df.iloc[i,5]=' Other'
for i in range(len(df)):
    if df.iloc[i,6]  in [' Protective-serv',' Armed-Forces',' Priv-house-serv']:
        df.iloc[i,6]=' Servants'

In [370]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()
le4=LabelEncoder()
le5=LabelEncoder()
le6=LabelEncoder()
le7=LabelEncoder()
le8=LabelEncoder()
le9=LabelEncoder()
le10=LabelEncoder()
df['Work Class ']=le1.fit_transform(df['Work Class '])
df['Education']=le2.fit_transform(df['Education'])
df['Marital Status']=le3.fit_transform(df['Marital Status'])
df['Occupation']=le4.fit_transform(df['Occupation'])
df['Education']=le5.fit_transform(df['Education'])
df['Relationship']=le6.fit_transform(df['Relationship'])
df['Race']=le7.fit_transform(df['Race'])
df['Sex']=le8.fit_transform(df['Sex'])
df['Native Country']=le9.fit_transform(df['Native Country'])
df['Income']=le10.fit_transform(df['Income'])

In [371]:
df.corr()

,Age,Work Class,fnlwgt,Education,Education num,Marital Status,Occupation,Relationship,Race,Sex,Capital Gain,Capital Loss,Hours Per Week,Native Country,Income
Age,1.000000,-0.210491,-0.076511,-0.039716,0.043526,-0.254936,-0.012280,-0.246456,0.023374,0.081993,0.080154,0.060165,0.101599,0.039511,0.241998
Work Class,-0.210491,1.000000,0.046589,0.058257,-0.165069,0.085511,-0.008662,0.087619,0.003045,-0.066803,-0.048185,-0.036377,-0.095533,-0.004509,-0.117218
fnlwgt,-0.076511,0.046589,1.000000,0.025333,-0.044992,0.034241,0.002277,0.009298,-0.023895,0.025362,0.000422,-0.009750,-0.022886,-0.050880,-0.008957
Education,-0.039716,0.058257,0.025333,1.000000,-0.568206,0.063278,-0.008044,0.067874,-0.022503,-0.010982,-0.026687,-0.031103,-0.124274,-0.046193,-0.158289
Education num,0.043526,-0.165069,-0.044992,-0.568206,1.000000,-0.073244,0.059118,-0.091935,0.032805,0.006157,0.124416,0.079646,0.152522,0.091703,0.335286
Marital Status,-0.254936,0.085511,0.034241,0.063278,-0.073244,1.000000,0.027607,0.194210,-0.080597,-0.134194,-0.042574,-0.036862,-0.180100,0.013914,-0.196538
Occupation,-0.012280,-0.008662,0.002277,-0.008044,0.059118,0.027607,1.000000,-0.035405,-0.011479,0.043696,0.014189,0.008114,0.002238,0.009744,0.028871
Relationship,-0.246456,0.087619,0.009298,0.067874,-0.091935,0.194210,-0.035405,1.000000,-0.117143,-0.584876,-0.058259,-0.063567,-0.257850,0.020876,-0.251003
Race,0.023374,0.003045,-0.023895,-0.022503,0.032805,-0.080597,-0.011479,-0.117143,1.000000,0.089186,0.014353,0.023517,0.048532,-0.243447,0.071658
Sex,0.081993,-0.066803,0.025362,-0.010982,0.006157,-0.134194,0.043696,-0.584876,0.089186,1.000000,0.048814,0.047011,0.231268,-0.030852,0.216699
Capital Gain,0.080154,-0.048185,0.000422,-0.026687,0.124416,-0.042574,0.014189,-0.058259,0.014353,0.048814,1.000000,-0.032229,0.080432,0.001684,0.221196
Capital Loss,0.060165,-0.036377,-0.009750,-0.031103,0.079646,-0.036862,0.008114,-0.063567,0.023517,0.047011,-0.032229,1.000000,0.052417,0.006876,0.150053
Hours Per Week,0.101599,-0.095533,-0.022886,-0.124274,0.152522,-0.180100,0.002238,-0.257850,0.048532,0.231268,0.080432,0.052417,1.000000,-0.006282,0.229480
Native Country,0.039511,-0.004509,-0.050880,-0.046193,0.091703,0.013914,0.009744,0.020876,-0.243447,-0.030852,0.001684,0.006876,-0.006282,1.000000,0.023304
Income,0.241998,-0.117218,-0.008957,-0.158289,0.335286,-0.196538,0.028871,-0.251003,0.071658,0.216699,0.221196,0.150053,0.229480,0.023304,1.000000

In [398]:
df=pd.read_csv("C:\\Users\\HP\\Downloads\\uci-census-income\\adults_train.csv")
test=pd.read_csv("C:\\Users\\HP\\Downloads\\uci-census-income\\adults_test.csv")

In [399]:
df=df[df['Work Class ']!=' ?']
df=df[df['Occupation']!=' ?']
df=df[df['Native Country']!=' ?']
for i in range(len(df)):
    if df.iloc[i,13] not in [' United-States',' Mexico']:
        df.iloc[i,13]='Other Country'
for i in range(len(df)):
    if df.iloc[i,3] in [' 1st-4th',' Preschool',' 5th-6th',' 10th', ' 12th',' 11th', ' 7th-8th',' 9th']:
        df.iloc[i,3]='12th and below'
for i in range(len(df)):
    if df.iloc[i,1] not in [' Private']:
        df.iloc[i,1]=' Not Private'
for i in range(len(df)):
    if df.iloc[i,5]  in [' Married-spouse-absent',' Separated',' Married-AF-spouse',' Widowed']:
        df.iloc[i,5]=' Other'
for i in range(len(df)):
    if df.iloc[i,6]  in [' Protective-serv',' Armed-Forces',' Priv-house-serv']:
        df.iloc[i,6]=' Servants'
test=test[test['Work Class ']!=' ?']
test=test[test['Occupation']!=' ?']
test=test[test['Native Country']!=' ?']
for i in range(len(test)):
    if test.iloc[i,13] not in [' United-States',' Mexico']:
        test.iloc[i,13]='Other Country'
for i in range(len(test)):
    if test.iloc[i,3] in [' 1st-4th',' Preschool',' 5th-6th',' 10th', ' 12th',' 11th', ' 7th-8th',' 9th']:
        test.iloc[i,3]='12th and below'
for i in range(len(test)):
    if test.iloc[i,1] not in [' Private']:
        test.iloc[i,1]=' Not Private'
for i in range(len(test)):
    if test.iloc[i,5]  in [' Married-spouse-absent',' Separated',' Married-AF-spouse',' Widowed']:
        test.iloc[i,5]=' Other'
for i in range(len(test)):
    if test.iloc[i,6]  in [' Protective-serv',' Armed-Forces',' Priv-house-serv']:
        test.iloc[i,6]=' Servants'

In [400]:
for i in range(len(test)):
    if test.iloc[i,14]==' <=50K.':
            test.iloc[i,14]=' <=50K'
    if test.iloc[i,14]==' >50K.':
            test.iloc[i,14]=' >50K'

In [401]:
df=df.drop(columns=['fnlwgt','Occupation','Native Country','Race'])
df=pd.get_dummies(data=df,columns=['Work Class ','Education','Marital Status','Relationship','Sex'],drop_first=True)
test=test.dropna(axis=0)
test=test.drop(columns=['fnlwgt','Occupation','Native Country','Race'])
test=pd.get_dummies(data=test,columns=['Work Class ','Education','Marital Status','Relationship','Sex'],drop_first=True)

In [402]:
le11=LabelEncoder()
df['Income']=le11.fit_transform(df['Income'])

In [403]:
test['Income']=le11.transform(test['Income'])

In [404]:
df=df[['Age', 'Education num', 'Capital Gain', 'Capital Loss',
       'Hours Per Week', 'Work Class _ Private',
       'Education_ Assoc-voc', 'Education_ Bachelors', 'Education_ Doctorate',
       'Education_ HS-grad', 'Education_ Masters', 'Education_ Prof-school',
       'Education_ Some-college', 'Education_12th and below',
       'Marital Status_ Married-civ-spouse', 'Marital Status_ Never-married',
       'Marital Status_ Other', 'Relationship_ Not-in-family',
       'Relationship_ Other-relative', 'Relationship_ Own-child',
       'Relationship_ Unmarried', 'Relationship_ Wife', 'Sex_ Male','Income']]

In [405]:
test=test[['Age', 'Education num', 'Capital Gain', 'Capital Loss',
       'Hours Per Week', 'Work Class _ Private',
       'Education_ Assoc-voc', 'Education_ Bachelors', 'Education_ Doctorate',
       'Education_ HS-grad', 'Education_ Masters', 'Education_ Prof-school',
       'Education_ Some-college', 'Education_12th and below',
       'Marital Status_ Married-civ-spouse', 'Marital Status_ Never-married',
       'Marital Status_ Other', 'Relationship_ Not-in-family',
       'Relationship_ Other-relative', 'Relationship_ Own-child',
       'Relationship_ Unmarried', 'Relationship_ Wife', 'Sex_ Male','Income']]

In [406]:
Xtrain=df.iloc[:,:-1]
ytrain=df.iloc[:,-1]
Xtest=test.iloc[:,:-1]
ytest=test.iloc[:,-1]

In [408]:
from xgboost import XGBClassifier

In [409]:
xgb=XGBClassifier()

In [410]:
xgb.fit(Xtrain,ytrain)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [414]:
ypred=xgb.predict(Xtest)

In [416]:
confusion_matrix(ytest,ypred)

array([[2519,  166],
       [ 334,  535]], dtype=int64)

In [419]:
accuracy_score(ytest,ypred)

0.859313449634215